-- Backup URLs avant migration Cloudinary — 2026-03-09 17:54:47
-- Pour rollback : importer ce fichier dans topspaceideal

UPDATE `produits` SET `image_produits` = 'avatar/client_avatar_38388.png', `image_produits1` = 'avatar/client_avatar_38388.png', `image_produits2` = 'avatar/client_avatar_38388.png' WHERE `id_produits` = 1;
UPDATE `produits` SET `image_produits` = 'members/1/client_produits.jpeg', `image_produits1` = 'members/1/client_produits1.jpeg', `image_produits2` = 'members/1/client_produits2.jpeg' WHERE `id_produits` = 2;
UPDATE `produits` SET `image_produits` = 'members/8/client_produits0_879094.jpg', `image_produits1` = 'members/8/client_produits1_165770.jpg', `image_produits2` = 'members/8/client_produits2_604706.jpg' WHERE `id_produits` = 3;
UPDATE `produits` SET `image_produits` = 'members/administrateur/4/user_produits0_5328.jpg', `image_produits1` = 'members/administrateur/4/user_produits1_370399.jpg', `image_produits2` = 'members/administrateur/4/user_produits2_798983.jpg' WHERE `id_produits` = 4;
UPDATE `produits` SET `image_produits` = 'members/10/client_produits0_659325.jpg', `image_produits1` = 'members/10/client_produits1_326109.jpg', `image_produits2` = 'members/10/client_produits2_726201.jpg' WHERE `id_produits` = 5;
UPDATE `produits` SET `image_produits` = 'members/15/client_produits0_667527.jpeg', `image_produits1` = 'members/15/client_produits1_677417.jpeg', `image_produits2` = 'members/15/client_produits2_170037.jpeg' WHERE `id_produits` = 8;
UPDATE `produits` SET `image_produits` = 'members/administrateur/4/user_produits0_921231.jpg', `image_produits1` = 'members/administrateur/4/user_produits1_939961.jpg', `image_produits2` = 'members/administrateur/4/user_produits2_57606.jpg' WHERE `id_produits` = 9;
UPDATE `produits` SET `image_produits` = 'members/administrateur/1/user_produits0_705958.jpeg', `image_produits1` = 'members/administrateur/1/user_produits1_517586.jpeg', `image_produits2` = 'members/administrateur/1/user_produits2_849914.jpeg' WHERE `id_produits` = 10;
UPDATE `produits` SET `image_produits` = 'members/17/client_produits0_420936.jpg', `image_produits1` = 'members/17/client_produits1_77336.jpg', `image_produits2` = 'members/17/client_produits2_413030.jpg' WHERE `id_produits` = 11;
UPDATE `produits` SET `image_produits` = 'members/14/client_produits0_428558.jpeg', `image_produits1` = 'members/14/client_produits1_447850.jpeg', `image_produits2` = 'members/14/client_produits2_657530.jpeg' WHERE `id_produits` = 14;
UPDATE `produits` SET `image_produits` = 'members/16/client_produits0_539567.jpeg', `image_produits1` = 'members/16/client_produits1_382212.jpeg', `image_produits2` = 'members/16/client_produits2_137990.jpeg' WHERE `id_produits` = 17;
UPDATE `produits` SET `image_produits` = 'members/4/client_produits0_198547.jpg', `image_produits1` = 'members/4/client_produits1_341124.jpg', `image_produits2` = 'members/4/client_produits2_765139.jpg' WHERE `id_produits` = 18;
UPDATE `produits` SET `image_produits` = 'members/21/client_produits0_110345.jpeg', `image_produits1` = 'members/21/client_produits1_852892.jpeg', `image_produits2` = 'members/21/client_produits2_240846.jpeg' WHERE `id_produits` = 19;
UPDATE `produits` SET `image_produits` = 'members/26/client_produits0_79776.jpeg', `image_produits1` = 'members/26/client_produits1_792605.jpeg', `image_produits2` = 'members/26/client_produits2_524261.jpeg' WHERE `id_produits` = 20;
UPDATE `produits` SET `image_produits` = 'members/25/client_produits0_305082.jpeg', `image_produits1` = 'members/25/client_produits1_278744.jpeg', `image_produits2` = 'members/25/client_produits2_107894.jpeg' WHERE `id_produits` = 21;
UPDATE `produits` SET `image_produits` = 'members/24/client_produits0_193163.jpg', `image_produits1` = 'members/24/client_produits1_792145.jpg', `image_produits2` = 'members/24/client_produits2_75717.jpg' WHERE `id_produits` = 22;
UPDATE `produits` SET `image_produits` = 'members/4/client_produits0_465704.jpg', `image_produits1` = 'members/4/client_produits1_849880.jpg', `image_produits2` = 'members/4/client_produits2_290555.jpg' WHERE `id_produits` = 23;
UPDATE `produits` SET `image_produits` = 'members/3/client_produits0_529764.jpg', `image_produits1` = 'members/3/client_produits1_629050.jpg', `image_produits2` = 'members/3/client_produits2_599775.jpg' WHERE `id_produits` = 24;
UPDATE `produits` SET `image_produits` = 'members/3/client_produits0_856980.jpg', `image_produits1` = 'members/3/client_produits1_788252.jpg', `image_produits2` = 'members/3/client_produits2_579158.jpg' WHERE `id_produits` = 25;
UPDATE `produits` SET `image_produits` = 'members/3/client_produits0_15784.jpg', `image_produits1` = 'members/3/client_produits1_716283.jpg', `image_produits2` = 'members/3/client_produits2_768706.jpg' WHERE `id_produits` = 26;
UPDATE `produits` SET `image_produits` = 'members/29/client_produits0_895178.jpeg', `image_produits1` = 'members/29/client_produits1_295270.jpeg', `image_produits2` = 'members/29/client_produits2_702341.jpeg' WHERE `id_produits` = 27;
UPDATE `produits` SET `image_produits` = 'members/29/client_produits0_607022.png', `image_produits1` = 'members/29/client_produits1_384985.png', `image_produits2` = 'members/29/client_produits2_241368.png' WHERE `id_produits` = 28;
UPDATE `produits` SET `image_produits` = 'members/32/client_produits0_180974.jpg', `image_produits1` = 'members/32/client_produits1_822466.jpg', `image_produits2` = 'members/32/client_produits2_775193.jpg' WHERE `id_produits` = 29;
UPDATE `produits` SET `image_produits` = 'members/3/client_produits0_177172.png', `image_produits1` = 'members/3/client_produits1_994417.jpg', `image_produits2` = 'members/3/client_produits2_646492.jpg' WHERE `id_produits` = 30;
UPDATE `produits` SET `image_produits` = 'members/3/client_produits0_37484.jpg', `image_produits1` = 'members/3/client_produits1_719422.jpg', `image_produits2` = 'members/3/client_produits2_191971.jpg' WHERE `id_produits` = 31;
UPDATE `produits` SET `image_produits` = 'members/40/client_produits0_477895.jpeg', `image_produits1` = 'members/40/client_produits1_308138.jpeg', `image_produits2` = 'members/40/client_produits2_932547.jpeg' WHERE `id_produits` = 32;
UPDATE `produits` SET `image_produits` = 'members/41/client_produits0_783262.png', `image_produits1` = 'members/41/client_produits1_406322.png', `image_produits2` = 'members/41/client_produits2_705087.png' WHERE `id_produits` = 33;
UPDATE `produits` SET `image_produits` = 'members/42/client_produits0_584668.png', `image_produits1` = 'members/42/client_produits1_346912.png', `image_produits2` = 'members/42/client_produits2_820836.png' WHERE `id_produits` = 34;
UPDATE `produits` SET `image_produits` = 'members/43/client_produits0_289481.png', `image_produits1` = 'members/43/client_produits1_361708.png', `image_produits2` = 'members/43/client_produits2_784988.png' WHERE `id_produits` = 35;
UPDATE `produits` SET `image_produits` = 'members/45/client_produits0_789137.jpeg', `image_produits1` = 'members/45/client_produits1_856200.jpeg', `image_produits2` = 'members/45/client_produits2_980956.jpeg' WHERE `id_produits` = 36;
UPDATE `produits` SET `image_produits` = 'members/36/client_produits0_942860.jpg', `image_produits1` = 'members/36/client_produits1_617798.jpg', `image_produits2` = 'members/36/client_produits2_609379.jpg' WHERE `id_produits` = 38;
UPDATE `produits` SET `image_produits` = 'members/37/client_produits0_98985.jpg', `image_produits1` = 'members/37/client_produits1_927102.jpg', `image_produits2` = 'members/37/client_produits2_646359.jpg' WHERE `id_produits` = 39;
UPDATE `produits` SET `image_produits` = 'members/51/client_produits0_331734.jpg', `image_produits1` = 'members/51/client_produits1_218292.jpg', `image_produits2` = 'members/51/client_produits2_850545.jpg' WHERE `id_produits` = 40;
UPDATE `produits` SET `image_produits` = 'members/53/client_produits0_50626.jpg', `image_produits1` = 'members/53/client_produits1_185969.jpg', `image_produits2` = 'members/53/client_produits2_460915.jpg' WHERE `id_produits` = 41;
UPDATE `produits` SET `image_produits` = 'members/54/client_produits0_296760.jpeg', `image_produits1` = 'members/54/client_produits1_452525.jpeg', `image_produits2` = 'members/54/client_produits2_995896.jpeg' WHERE `id_produits` = 42;
UPDATE `produits` SET `image_produits` = 'members/54/client_produits0_780203.jpeg', `image_produits1` = 'members/54/client_produits1_575571.jpeg', `image_produits2` = 'members/54/client_produits2_84221.jpeg' WHERE `id_produits` = 43;
UPDATE `produits` SET `image_produits` = 'members/46/client_produits0_478120.jpg', `image_produits1` = 'members/46/client_produits1_917195.jpg', `image_produits2` = 'members/46/client_produits2_221922.jpg' WHERE `id_produits` = 44;
UPDATE `produits` SET `image_produits` = 'members/45/client_produits0_881515.jpg', `image_produits1` = 'members/45/client_produits1_672544.jpg', `image_produits2` = 'members/45/client_produits2_216569.jpg' WHERE `id_produits` = 48;
UPDATE `produits` SET `image_produits` = 'members/51/client_produits0_765539.jpg', `image_produits1` = 'members/51/client_produits1_876369.jpg', `image_produits2` = 'members/51/client_produits2_68790.jpg' WHERE `id_produits` = 49;
UPDATE `produits` SET `image_produits` = 'members/1/client_produits0_879787.jpeg', `image_produits1` = 'members/1/client_produits1_740598.jpeg', `image_produits2` = 'members/1/client_produits2_451801.jpeg' WHERE `id_produits` = 50;
UPDATE `produits` SET `image_produits` = 'members/59/client_produits0_672553.jpg', `image_produits1` = 'members/59/client_produits1_301207.jpg', `image_produits2` = 'members/59/client_produits2_205654.jpg' WHERE `id_produits` = 52;
UPDATE `produits` SET `image_produits` = 'members/59/client_produits0_490810.jpg', `image_produits1` = 'members/59/client_produits1_884725.jpg', `image_produits2` = 'members/59/client_produits2_149181.jpg' WHERE `id_produits` = 53;
UPDATE `produits` SET `image_produits` = 'members/59/client_produits0_2632.jpg', `image_produits1` = 'members/59/client_produits1_265345.jpg', `image_produits2` = 'members/59/client_produits2_93009.jpg' WHERE `id_produits` = 54;
UPDATE `produits` SET `image_produits` = 'members/59/client_produits0_807113.jpg', `image_produits1` = 'members/59/client_produits1_578137.jpg', `image_produits2` = 'members/59/client_produits2_77061.jpg' WHERE `id_produits` = 55;
UPDATE `produits` SET `image_produits` = 'members/59/client_produits0_377892.jpg', `image_produits1` = 'members/59/client_produits1_422595.jpg', `image_produits2` = 'members/59/client_produits2_940351.jpg' WHERE `id_produits` = 56;
UPDATE `produits` SET `image_produits` = 'members/62/client_produits0_866214.jpg', `image_produits1` = 'members/62/client_produits1_681432.jpg', `image_produits2` = 'members/62/client_produits2_382208.jpg' WHERE `id_produits` = 57;
UPDATE `produits` SET `image_produits` = 'members/62/client_produits0_663531.jpg', `image_produits1` = 'members/62/client_produits1_51595.jpg', `image_produits2` = 'members/62/client_produits2_186680.jpg' WHERE `id_produits` = 58;
UPDATE `produits` SET `image_produits` = 'members/61/client_produits0_333293.jpg', `image_produits1` = 'members/61/client_produits1_312404.jpg', `image_produits2` = 'members/61/client_produits2_864441.jpg' WHERE `id_produits` = 59;
UPDATE `produits` SET `image_produits` = 'members/52/client_produits0_875084.jpg', `image_produits1` = 'members/52/client_produits1_836328.jpg', `image_produits2` = 'members/52/client_produits2_902328.jpg' WHERE `id_produits` = 60;
UPDATE `produits` SET `image_produits` = 'members/52/client_produits0_89723.jpg', `image_produits1` = 'members/52/client_produits1_684258.jpg', `image_produits2` = 'members/52/client_produits2_622217.jpg' WHERE `id_produits` = 61;
UPDATE `produits` SET `image_produits` = 'members/63/client_produits0_558365.jpeg', `image_produits1` = 'members/63/client_produits1_316257.jpeg', `image_produits2` = 'members/63/client_produits2_241371.jpeg' WHERE `id_produits` = 62;
UPDATE `produits` SET `image_produits` = 'members/63/client_produits0_54764.jpeg', `image_produits1` = 'members/63/client_produits1_94932.jpeg', `image_produits2` = 'members/63/client_produits2_981189.jpeg' WHERE `id_produits` = 63;
UPDATE `produits` SET `image_produits` = 'members/63/client_produits0_333331.jpeg', `image_produits1` = 'members/63/client_produits1_977318.jpeg', `image_produits2` = 'members/63/client_produits2_232486.jpeg' WHERE `id_produits` = 65;
UPDATE `produits` SET `image_produits` = 'members/68/client_produits0_688551.jpg', `image_produits1` = 'members/68/client_produits1_522796.jpg', `image_produits2` = 'members/68/client_produits2_709092.jpg' WHERE `id_produits` = 67;
UPDATE `produits` SET `image_produits` = 'members/39/client_produits0_775460.jpg', `image_produits1` = 'members/39/client_produits1_525569.jpg', `image_produits2` = 'members/39/client_produits2_750704.jpg' WHERE `id_produits` = 68;
UPDATE `produits` SET `image_produits` = 'members/70/client_produits0_797980.png', `image_produits1` = 'members/70/client_produits1_70533.png', `image_produits2` = 'members/70/client_produits2_233879.png' WHERE `id_produits` = 69;
UPDATE `produits` SET `image_produits` = 'members/70/client_produits0_969464.png', `image_produits1` = 'members/70/client_produits1_389024.png', `image_produits2` = 'members/70/client_produits2_460849.png' WHERE `id_produits` = 71;
UPDATE `produits` SET `image_produits` = 'members/39/client_produits0_129528.jpg', `image_produits1` = 'members/39/client_produits1_625443.jpg', `image_produits2` = 'members/39/client_produits2_429869.jpg' WHERE `id_produits` = 72;
UPDATE `produits` SET `image_produits` = 'members/37/client_produits0_619234.jpg', `image_produits1` = 'members/37/client_produits1_989177.jpg', `image_produits2` = 'members/37/client_produits2_657605.jpg' WHERE `id_produits` = 73;
UPDATE `produits` SET `image_produits` = 'members/56/client_produits0_992818.jpg', `image_produits1` = 'members/56/client_produits1_788946.jpg', `image_produits2` = 'members/56/client_produits2_728744.jpg' WHERE `id_produits` = 74;
UPDATE `produits` SET `image_produits` = 'members/56/client_produits0_657234.jpg', `image_produits1` = 'members/56/client_produits1_733646.jpg', `image_produits2` = 'members/56/client_produits2_98482.jpg' WHERE `id_produits` = 75;
UPDATE `produits` SET `image_produits` = 'members/56/client_produits0_762372.jpg', `image_produits1` = 'members/56/client_produits1_670400.jpg', `image_produits2` = 'members/56/client_produits2_695982.jpg' WHERE `id_produits` = 76;
UPDATE `produits` SET `image_produits` = 'members/56/client_produits0_542299.jpg', `image_produits1` = 'members/56/client_produits1_868104.jpg', `image_produits2` = 'members/56/client_produits2_476956.jpg' WHERE `id_produits` = 77;
UPDATE `produits` SET `image_produits` = 'members/56/client_produits0_464270.png', `image_produits1` = 'members/56/client_produits1_774225.png', `image_produits2` = 'members/56/client_produits2_634932.png' WHERE `id_produits` = 78;
UPDATE `produits` SET `image_produits` = 'members/97/client_produits0_138908.jpg', `image_produits1` = 'members/97/client_produits1_170420.jpg', `image_produits2` = 'members/97/client_produits2_914959.jpg' WHERE `id_produits` = 79;
UPDATE `produits` SET `image_produits` = 'members/103/client_produits0_180093.jpg', `image_produits1` = 'members/103/client_produits1_731140.jpg', `image_produits2` = 'members/103/client_produits2_760146.jpg' WHERE `id_produits` = 80;
UPDATE `produits` SET `image_produits` = 'members/120/client_produits0_854628.jpg', `image_produits1` = 'members/120/client_produits1_545676.jpg', `image_produits2` = 'members/120/client_produits2_136805.jpg' WHERE `id_produits` = 82;
UPDATE `produits` SET `image_produits` = 'members/125/client_produits0_450301.jpg', `image_produits1` = 'members/125/client_produits1_100261.jpg', `image_produits2` = 'members/125/client_produits2_805201.jpg' WHERE `id_produits` = 84;
UPDATE `produits` SET `image_produits` = 'members/125/client_produits0_498130.jpg', `image_produits1` = 'members/125/client_produits1_654894.jpg', `image_produits2` = 'members/125/client_produits2_66944.jpg' WHERE `id_produits` = 85;
UPDATE `produits` SET `image_produits` = 'members/125/client_produits0_603007.jpg', `image_produits1` = 'members/125/client_produits1_109991.jpg', `image_produits2` = 'members/125/client_produits2_175073.jpg' WHERE `id_produits` = 86;
UPDATE `produits` SET `image_produits` = 'members/125/client_produits0_648468.jpg', `image_produits1` = 'members/125/client_produits1_870171.jpg', `image_produits2` = 'members/125/client_produits2_878912.jpg' WHERE `id_produits` = 87;
UPDATE `produits` SET `image_produits` = 'members/125/client_produits0_147284.jpg', `image_produits1` = 'members/125/client_produits1_652070.jpg', `image_produits2` = 'members/125/client_produits2_521125.jpg' WHERE `id_produits` = 88;
UPDATE `produits` SET `image_produits` = 'members/126/client_produits0_779069.jpg', `image_produits1` = 'members/126/client_produits1_632677.jpg', `image_produits2` = 'members/126/client_produits2_469473.jpg' WHERE `id_produits` = 89;
UPDATE `produits` SET `image_produits` = 'members/128/client_produits0_239078.jpg', `image_produits1` = 'members/128/client_produits1_2447.jpg', `image_produits2` = 'members/128/client_produits2_915504.jpg' WHERE `id_produits` = 90;
UPDATE `produits` SET `image_produits` = 'members/129/client_produits0_752532.jpg', `image_produits1` = 'members/129/client_produits1_894196.jpg', `image_produits2` = 'members/129/client_produits2_388834.jpg' WHERE `id_produits` = 91;
UPDATE `produits` SET `image_produits` = 'members/130/client_produits0_94992.jpg', `image_produits1` = 'members/130/client_produits1_201219.jpg', `image_produits2` = 'members/130/client_produits2_789524.jpg' WHERE `id_produits` = 92;
UPDATE `produits` SET `image_produits` = 'members/131/client_produits0_617434.jpg', `image_produits1` = 'members/131/client_produits1_846488.jpg', `image_produits2` = 'members/131/client_produits2_971447.jpg' WHERE `id_produits` = 93;
UPDATE `produits` SET `image_produits` = 'members/135/client_produits0_330533.png', `image_produits1` = 'members/135/client_produits1_188695.png', `image_produits2` = 'members/135/client_produits2_943609.png' WHERE `id_produits` = 94;
UPDATE `produits` SET `image_produits` = 'members/138/client_produits0_845856.jpg', `image_produits1` = 'members/138/client_produits1_868693.jpg', `image_produits2` = 'members/138/client_produits2_758206.jpg' WHERE `id_produits` = 95;
UPDATE `produits` SET `image_produits` = 'members/139/client_produits0_835614.jpg', `image_produits1` = 'members/139/client_produits1_84228.jpg', `image_produits2` = 'members/139/client_produits2_236677.jpg' WHERE `id_produits` = 96;
UPDATE `produits` SET `image_produits` = 'members/142/client_produits0_164339.png', `image_produits1` = 'members/142/client_produits1_372056.png', `image_produits2` = 'members/142/client_produits2_256092.png' WHERE `id_produits` = 97;
UPDATE `produits` SET `image_produits` = 'members/142/client_produits0_820520.png', `image_produits1` = 'members/142/client_produits1_291162.png', `image_produits2` = 'members/142/client_produits2_746762.png' WHERE `id_produits` = 98;
UPDATE `produits` SET `image_produits` = 'members/135/client_produits0_748065.jpg', `image_produits1` = 'members/135/client_produits1_470796.jpg', `image_produits2` = 'members/135/client_produits2_9799.jpg' WHERE `id_produits` = 99;
UPDATE `produits` SET `image_produits` = 'members/143/client_produits0_16972.jpg', `image_produits1` = 'members/143/client_produits1_737356.jpg', `image_produits2` = 'members/143/client_produits2_903435.jpg' WHERE `id_produits` = 102;
UPDATE `produits` SET `image_produits` = 'members/125/client_produits0_96174.jpg', `image_produits1` = 'members/125/client_produits1_56099.jpg', `image_produits2` = 'members/125/client_produits2_290342.jpg' WHERE `id_produits` = 103;
UPDATE `produits` SET `image_produits` = 'members/152/client_produits0_259378.jpeg', `image_produits1` = 'members/152/client_produits1_975780.jpeg', `image_produits2` = 'members/152/client_produits2_994630.jpeg' WHERE `id_produits` = 104;
UPDATE `produits` SET `image_produits` = 'members/152/client_produits0_71226.jpeg', `image_produits1` = 'members/152/client_produits1_678028.jpeg', `image_produits2` = 'members/152/client_produits2_805550.jpeg' WHERE `id_produits` = 105;
UPDATE `produits` SET `image_produits` = 'members/151/client_produits0_373397.jpg', `image_produits1` = 'members/151/client_produits1_775296.jpg', `image_produits2` = 'members/151/client_produits2_839473.jpg' WHERE `id_produits` = 106;
UPDATE `produits` SET `image_produits` = 'members/153/client_produits0_441550.jpg', `image_produits1` = 'members/153/client_produits1_391090.jpg', `image_produits2` = 'members/153/client_produits2_118318.jpg' WHERE `id_produits` = 107;
UPDATE `produits` SET `image_produits` = 'members/160/client_produits0_184785.jpeg', `image_produits1` = 'members/160/client_produits1_245170.jpeg', `image_produits2` = 'members/160/client_produits2_455081.jpeg' WHERE `id_produits` = 109;
UPDATE `produits` SET `image_produits` = 'members/165/client_produits0_730415.jpg', `image_produits1` = 'members/165/client_produits1_141772.jpg', `image_produits2` = 'members/165/client_produits2_622795.jpg' WHERE `id_produits` = 110;
UPDATE `clients` SET `image_client` = 'members/1/client_profil.jpeg' WHERE `id_client` = 1;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 2;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 3;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 4;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 6;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 7;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 8;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 9;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 10;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 11;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 12;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 13;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 14;
UPDATE `clients` SET `image_client` = 'members/15/client_profil.jpeg' WHERE `id_client` = 15;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 16;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 17;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 18;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 20;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 21;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 22;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 23;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 24;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 25;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 26;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 29;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 31;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 32;
UPDATE `clients` SET `image_client` = 'members/34/client_profil.jpg' WHERE `id_client` = 34;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 35;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 36;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 37;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 38;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 39;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 40;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 41;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 42;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 43;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 44;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 45;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 46;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 50;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 51;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 52;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 53;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 54;
UPDATE `clients` SET `image_client` = 'members/56/client_profil.jpg' WHERE `id_client` = 56;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 57;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 59;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 61;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 62;
UPDATE `clients` SET `image_client` = 'members/63/client_profil.jpeg' WHERE `id_client` = 63;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 64;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 67;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 68;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 69;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 70;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 74;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 76;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 79;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 80;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 81;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 83;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 85;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 86;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 87;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 88;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 92;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 95;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 96;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 97;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 98;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 100;
UPDATE `clients` SET `image_client` = 'members/101/client_profil.jpg' WHERE `id_client` = 101;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 103;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 108;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 110;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 111;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 112;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 113;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 114;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 115;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 117;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 118;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 119;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 120;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 121;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 123;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 124;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 125;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 126;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 127;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 128;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 129;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 130;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 131;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 132;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 134;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 135;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 137;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 138;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 139;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 140;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 141;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 142;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 143;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 144;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 145;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 146;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 147;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 148;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 149;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 150;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 151;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 152;
UPDATE `clients` SET `image_client` = 'members/153/client_profil.png' WHERE `id_client` = 153;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 154;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 155;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 157;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 158;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 159;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 160;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 161;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 162;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 164;
UPDATE `clients` SET `image_client` = 'members/165/client_profil.jpg' WHERE `id_client` = 165;
UPDATE `clients` SET `image_client` = 'dashimmo/avatar.png' WHERE `id_client` = 166;
UPDATE `sponsor` SET `image_sponsor` = '/members/administrateur/1/sponsor/sponsor_avatar_600114.jpg' WHERE `id_sponsor` = 13;
UPDATE `sponsor` SET `image_sponsor` = '/members/administrateur/1/sponsor/sponsor_avatar_244763.jpg' WHERE `id_sponsor` = 14;
UPDATE `sponsor` SET `image_sponsor` = '/members/administrateur/1/sponsor/sponsor_avatar_687441.jpg' WHERE `id_sponsor` = 15;
UPDATE `sponsor` SET `image_sponsor` = '/members/administrateur/1/sponsor/sponsor_avatar_511934.jpg' WHERE `id_sponsor` = 16;
UPDATE `sponsor` SET `image_sponsor` = '/members/administrateur/1/sponsor/sponsor_avatar_477631.jpeg' WHERE `id_sponsor` = 17;
UPDATE `sponsor` SET `image_sponsor` = '/members/administrateur/1/sponsor/sponsor_avatar_736114.jpeg' WHERE `id_sponsor` = 19;
UPDATE `sponsor` SET `image_sponsor` = 'members/97/sponsor/sponsor_avatar_102261.jpg' WHERE `id_sponsor` = 22;
UPDATE `sponsor` SET `image_sponsor` = 'members/126/sponsor/sponsor_avatar_733273.jpg' WHERE `id_sponsor` = 23;
UPDATE `sponsor` SET `image_sponsor` = 'members/125/sponsor/sponsor_avatar_586240.jpg' WHERE `id_sponsor` = 24;
UPDATE `sponsor` SET `image_sponsor` = 'members/125/sponsor/sponsor_avatar_349381.jpg' WHERE `id_sponsor` = 25;
UPDATE `sponsor` SET `image_sponsor` = 'members/165/sponsor/sponsor_avatar_222337.jpg' WHERE `id_sponsor` = 26;
UPDATE `categorie` SET `image_categorie` = 'categorie/categorie_avatar_931651.png' WHERE `id_categorie` = 1;
UPDATE `categorie` SET `image_categorie` = 'categorie/categorie_avatar_635165.png' WHERE `id_categorie` = 2;
UPDATE `categorie` SET `image_categorie` = 'categorie/categorie_avatar_488710.png' WHERE `id_categorie` = 3;
UPDATE `categorie` SET `image_categorie` = 'categorie/categorie_avatar_888688.png' WHERE `id_categorie` = 4;
UPDATE `categorie` SET `image_categorie` = 'categorie/categorie_avatar_745199.png' WHERE `id_categorie` = 5;
UPDATE `categorie` SET `image_categorie` = 'categorie/categorie_avatar_453089.png' WHERE `id_categorie` = 6;
UPDATE `categorie` SET `image_categorie` = 'categorie/categorie_avatar_348753.png' WHERE `id_categorie` = 7;
UPDATE `posts` SET `image1` = '../uploads/ima1.png', `image2` = '../uploads/ima2.png' WHERE `idposts` = 1;
UPDATE `posts` SET `image1` = '../uploads/n1.PNG', `image2` = '../uploads/n2.PNG' WHERE `idposts` = 2;
UPDATE `posts` SET `image1` = '../uploads/n1.PNG', `image2` = '../uploads/n2.PNG' WHERE `idposts` = 3;
UPDATE `posts` SET `image1` = '../uploads/n1.PNG', `image2` = '../uploads/n2.PNG' WHERE `idposts` = 4;
UPDATE `users` SET `image_user` = 'dashimmo/avatar.png' WHERE `id_user` = 1;
UPDATE `users` SET `image_user` = 'members/administrateur/4/user_profil.jpg' WHERE `id_user` = 4;
UPDATE `users` SET `image_user` = 'dashimmo/avatar.png' WHERE `id_user` = 5;
